### PR TITLE
Dev2

### PR DESCRIPTION
**Pull request by vsarsani**
Fixing the example runs. All th examples now run successfully. R CMD CHECK sometimes throws rxode compilation issues or inability to install nlmixr2 .

### CODE REVIEW

**Comment by billdenney** [comment]
@vsarsani After rerunning, there are still a few issues:

https://github.com/nlmixr2/nlmixr2extra/runs/8208828429?check_suite_focus=true#step:20:602

https://github.com/nlmixr2/nlmixr2extra/runs/8208828429?check_suite_focus=true#step:20:562

It's not clear if the following is a real issue or if it is related to the sink issue:

https://github.com/nlmixr2/nlmixr2extra/runs/8208828429?check_suite_focus=true#step:20:588

**Comment by vsarsani** [comment]
@billdenney 
I think the RMD check note error should be fixed.

I cannot replicate the last two issues of stan on my end and googling the error shows it has to do with the compilation/installation of stan 

https://discourse.mc-stan.org/t/error-in-sink-type-output-invalid-connection/20672

https://discourse.mc-stan.org/t/error-in-sink-type-output-invalid-connection-on-mac-os/26117

**Comment by billdenney** [comment]
I am reproducibly getting the Stan errors on my end, but it does seem to be a Stan thing.  For the moment, I think that the best solution would be to push your changes that fix the other issues and comment out the example line causing the stan issues with a comment above it noting that it should run (but it often has issues with Stan).

How does that sound for right now?

**Comment by vsarsani** [comment]
Done. Do you see these issues when you do devtools::load_all() and then run examples (let's say horseshoe) on your console?

**Comment by billdenney** [comment]
> Done. Do you see these issues when you do devtools::load_all() and then run examples (let's say horseshoe) on your console?

Yeah, that is how I was testing.  My test system is R 4.2.1 with Windows 11.  And, I tried reinstalling the stan packages from source, too.

**Comment by vsarsani** [comment]
Running devtools::document()

**Comment by vsarsani** [comment]
I have windows 11 R 4.2.0. Mine runs without any errors. I do have a WSL ubuntu and I will try to reproduce the error and see if I can resolve the output sink thing.

**Pull request merged**
