### PR TITLE
Initial commit of extract_eq() to generate LaTeX equations from models

### LINKED ISSUE #29: Feature request: equations generation
I find it easier to have discussions for features on the issues side and to have a more code-focused discussion on the PR side.  So, I'm opening this after the fact for PR #28.

A few notes:

1. I think that the easiest way to test the outputs is to run `cat(extract_eq())` with the model and then paste that into an online LaTeX formatter (e.g. https://quicklatex.com/) to check it.
2. I'm not so happy with the way that `if` blocks are formatted.  I'm open to any feedback on the formatting, and `if` blocks probably need some special attention.  (All ideas are welcome, even if they don't have a clear way to implement them in LaTeX to start.)
3. I have used math notation rather than code notation for some symbols (most notably the logical operators as shown by running https://github.com/nlmixr2/nlmixr2extra/blob/976014f7a647b47252902e5f2e17ae8b81d0e383/tests/testthat/test-extract_eq.R#L68).  I'm not sure if that is better (because it aligns more consistently with math) or worse (because it is farther from the model code).  I'm open to input there.  The code for the selected operators is at https://github.com/nlmixr2/nlmixr2extra/blob/976014f7a647b47252902e5f2e17ae8b81d0e383/R/extract_eq.R#L223-L236
4. It took some looking for how to handle named arguments (e.g. [`cp ~ c(p0=0, p1=1, p2=2, 3)`](https://github.com/nlmixr2/nlmixr2extra/blob/976014f7a647b47252902e5f2e17ae8b81d0e383/tests/testthat/test-extract_eq.R#L63)).  I put name handing in for character and numeric values in the parse tree.  It's not clear to me if there are situations where that will break.  (I didn't expect for the names to show up in the way that they do, so I don't fully understand that part of the parse tree.)  If you have ideas of other ways that names may show up, I want to check that I have that part right.
5. I don't think that there is significant benefit to matching the `extract_eq()` generic at this time.  And there is a downside of many ignored arguments.  If people may move between `nlmixr2` and other supported packages and want to use the same function for extraction, there is a benefit, but I don't know how common that is.  (I do it from time to time, but I'm likely in the minority.)

### PR DESCRIPTION
**Pull request by billdenney**
This is ready to try out.

Fixes #29

### CODE REVIEW

**Comment by billdenney** [comment]
The mac failure appears to be an issue with CI and not with the PR.  It should be fixed by merging with #30 (assuming that it completes successfully).

**Comment by billdenney** [comment]
Two additional features for consideration:  

* Too many equations and no page breaks: https://tex.stackexchange.com/questions/51682/is-it-possible-to-pagebreak-aligned-equations
* wrapping the equation right hand side

**Comment by billdenney** [comment]
@mattfidler, I think that this is ready to merge, if it works for you.

**Comment by mattfidler** [comment]
We see:

```
Found the following significant warnings:
  /Users/runner/work/_temp/Library/Rcpp/include/Rcpp/internal/r_coerce.h:255:7: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
```

**Comment by mattfidler** [comment]
This is already addressed, but not in Rcpp now I guess.

**Comment by mattfidler** [comment]
Looks good to me.  Thanks @billdenney

**Pull request merged**
