### PR TITLE
Update continuous integration

### LINKED ISSUE #39: Duplicated code
While trying to fix the random CI failures in nlmixr2/nlmixr2#68, I found that the issue seemed to come from memory issues related to building the bootstrap documentation.  When looking at the bootstrap documentation, I noticed that there is a lot of nearly identical code in bootstrap.R and computingutil.R.  Given the fact that they are nearly the same but not the same, I'm not sure which is preferred.  @mattfidler, can you please take a look and remove one of them:

https://github.com/nlmixr2/nlmixr2extra/blob/c13dc983af7d2f5933863210df64c4a5c962852c/R/bootstrap.R#L1-L1238

https://github.com/nlmixr2/nlmixr2extra/blob/c13dc983af7d2f5933863210df64c4a5c962852c/R/computingutil.R#L296-L1527

### PR DESCRIPTION
**Pull request by billdenney**
Fix #39 (integrates changes from #41 to try to get testing working)

### CODE REVIEW

**Comment by billdenney** [comment]
I have confirmed that all functions in boostrap.R were duplicates of functions in computingutils.R.  And, I removed bootstrap.R as @vsarsani suggested in #39.

**Comment by mattfidler** [comment]
Donttest does not make cran requirments.  Can you switch it back and we can figure out how to fix it for ci

**Comment by billdenney** [comment]
I'm doing this as a bifurcation test because I can't replicate the issues on my local system, and they are occurring in a donttest block.  I want to get to a working state, and then I will loosen the dontruns to donttests again.

**Comment by billdenney** [comment]
Shorter answer:  I will restore them to `donttests` when I find the issue.

**Comment by mattfidler** [comment]
Thats fine with me.

**Comment by billdenney** [comment]
@mattfidler, at this point, all of the `\dontrun`s appear to have issues with the CI when set to `\donttest`.  How would you like to proceed?

**Comment by mattfidler** [comment]
Well it wont be ready for cran until this is fixed.  Why dont we do the following for now:

- turn on dontrun for now
- mege it; merge the other pull requests

**Comment by mattfidler** [comment]
It could be because `nlmixr2est`, and `rxode2` were broken in general....  Mostly because of repdep issues.

I have tried to address this currently the tests are still running.

**Pull request merged**
