### PR TITLE
Vsarsani dev2

### PR DESCRIPTION
**Pull request by mattfidler**

### CODE REVIEW

**Comment by mattfidler** [comment]
@vsarsani Do you have an OCRID you wish to use in your authorship?

**Comment by vsarsani** [comment]
@mattfidler https://orcid.org/0000-0002-9272-3438

**Comment by vsarsani** [comment]
@mattfidler  using vapply instead of sapply throws errors during R CMD checks even though it is originally recommended by it.

**Comment by mattfidler** [comment]
Hm.  There is no error with this version of `vapply`

**Pull request merged**
